[metadata]
name = tower
version = 1.0
description =  
long_description =
licence =
classifiers =
    Programming Langauge :: python :: 3

[options]
zip_safe = false
packages = find:
install_requires = 
    click==8.*
    pygame==2.*
    structlog

[options.package_data]
tower.assets.gfx = *.png
tower.assets.audio = *.wav, *.ogg
tower.assets.levels = *.json

[options.entry_points]
console_scripts =
    tower = src.main:main
