[metadata]
name = tower
version = 1.0
description =  A tower defense game built in Python using pygame
long_description = file: README.md
license = MIT
classifiers =
    Programming Language :: Python :: 3

[options]
zip_safe = false
package_dir =
    = src
packages = find:

[options.packages.find]
where = src

install_requires = 
    click==8.*
    pygame==2.*
    structlog

[options.package_data]
tower.assets.gfx = *.png
tower.assets.audio = *.wav, *.ogg
tower.assets.levels = *.json

[options.entry_points]
console_scripts =
    tower = tower.main:main
